export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p >This is Header</p>
        </header>
        {children}
        <footer>
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  )
}
