import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
} 
// not able to use metadata bc of use client

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body>
        <div className="rounded-lg bg-red-200">
           {children}
        </div>
       
        <footer>
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  )
}
