'use client'

import "./style.css"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// } // not able to use metadata bc of use client

const navLinks = [
  {name : "Register" , href : "/register"},
  {name : "Login" , href : "/login"},
  {name : "Forget Password" , href : "/forget-password"},
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();

  const [input, setInput] = useState('');

  return (
    <html lang="en">
      <body>
        <div>
          <div>
            <input type="text" value={input} onChange={(e) => setInput(e.target.value) } />
          </div>
          {navLinks.map((link) => {
            const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/");
            return (
              <Link className={isActive ? "font-bold mr-4" : "text-blue-500 mr-4"} href={link.href} key={link.name}>
              {link.name}
              </Link>
            )
          })}
        </div>
        {children}
        {/* <footer>
          <p>This is footer</p>
        </footer> */}
      </body>
    </html>
  )
}
